fullnameOverride: devoops-reservation-service
replicaCount: 1

image:
  registry: docker.io
  repository: threeamigoscoding/devoops-reservation-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 8080
  grpc:
    enabled: true
    port: 9090

ingress:
  enabled: false

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 1000m

health:
  path: /actuator/health
  periodSeconds: 10
  failureThreshold: 3
  startup:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 60

configData:
  JAVA_TOOL_OPTIONS: "-XX:+UseSerialGC -Xms128m -Xmx384m -XX:ActiveProcessorCount=1"
  SERVER_PORT: "8080"
  LOGSTASH_HOST: "devoops-logstash:5000"
  ZIPKIN_HOST: "devoops-jaeger"
  ZIPKIN_PORT: "9411"
  POSTGRES_HOST: "devoops-postgres"
  POSTGRES_PORT: "5432"
  GRPC_PORT: "9090"
  ACCOMMODATION_GRPC_HOST: "devoops-accommodation-service"
  ACCOMMODATION_GRPC_PORT: "9090"
  RABBITMQ_HOST: "devoops-rabbitmq"
  RABBITMQ_PORT: "5672"

secretData:
  DB_USERNAME: "reservation-service"
  DB_PASSWORD: "reservation-service-pass"
  RABBITMQ_USERNAME: "devoops"
  RABBITMQ_PASSWORD: "devoops123"
